
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appDir = path.dirname(fileURLToPath(import.meta.url));
const defaultDbPath = path.join(appDir, "data", "jscalendar-tasks.db");
const defaultDbUrl = `file:${defaultDbPath}`;

function resolveDbUrl(raw: string | undefined) {
  if (!raw) {
    mkdirSync(path.dirname(defaultDbPath), { recursive: true });
    return defaultDbUrl;
  }
  if (!raw.startsWith("file:")) return raw;

  const dbPath = raw.slice("file:".length);
  if (path.isAbsolute(dbPath)) return raw;
  return `file:${path.resolve(appDir, dbPath)}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: resolveDbUrl(process.env["DATABASE_URL"]),
  },
});
